-- Idempotent import of Audi Price List 2.xlsx (25 catalog SKUs).
-- Images wired to /vehicles/audi-*.webp (Higgsfield heroes packaged into public/).

DO $$
DECLARE
  v_audi uuid;
BEGIN
  SELECT id INTO v_audi FROM public.companies WHERE name = 'Audi' LIMIT 1;
  IF v_audi IS NULL THEN
    RAISE EXCEPTION 'Audi company missing — run products_company_id migration first';
  END IF;

  -- Helper inline via VALUES upsert
  INSERT INTO public.products (
    id, make, model, trim, model_year, condition, engine, color, mileage, price,
    status, images, documents, attributes, description, company_id, created_at, updated_at
  )
  VALUES
    ('audi-a3-sedan-35-tfsi', 'Audi', 'A3', 'Sedan 35 TFSI', 2026, 'new', '35 TFSI', 'Florett Silver', 0, 155000, 'active',
      '["/vehicles/audi-a3-sedan-35-tfsi.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"Sedan"},{"id":"performance_line","name":"performance_line","value":"A"},{"id":"model_family_key","name":"model_family_key","value":"a3"},{"id":"sku_key","name":"sku_key","value":"audi-a3-sedan-35-tfsi"}]'::jsonb,
      'Audi A3 Sedan 35 TFSI', v_audi, now(), now()),
    ('audi-s3-sportback', 'Audi', 'S3', 'Sportback', 2026, 'new', 'S3', 'Daytona Grey', 0, 255000, 'active',
      '["/vehicles/audi-s3-sportback.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"Sportback"},{"id":"performance_line","name":"performance_line","value":"S"},{"id":"model_family_key","name":"model_family_key","value":"s3"},{"id":"sku_key","name":"sku_key","value":"audi-s3-sportback"}]'::jsonb,
      'Audi S3 Sportback', v_audi, now(), now()),
    ('audi-s3-sedan', 'Audi', 'S3', 'Sedan', 2026, 'new', 'S3', 'Daytona Grey', 0, 265000, 'active',
      '["/vehicles/audi-s3-sedan.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"Sedan"},{"id":"performance_line","name":"performance_line","value":"S"},{"id":"model_family_key","name":"model_family_key","value":"s3"},{"id":"sku_key","name":"sku_key","value":"audi-s3-sedan"}]'::jsonb,
      'Audi S3 Sedan', v_audi, now(), now()),
    ('audi-rs3-sportback', 'Audi', 'RS3', 'Sportback', 2026, 'new', 'RS3', 'Nardo Grey', 0, 335000, 'active',
      '["/vehicles/audi-rs3-sportback.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"Sportback"},{"id":"performance_line","name":"performance_line","value":"RS"},{"id":"model_family_key","name":"model_family_key","value":"rs3"},{"id":"sku_key","name":"sku_key","value":"audi-rs3-sportback"}]'::jsonb,
      'Audi RS3 Sportback', v_audi, now(), now()),
    ('audi-rs3-sedan', 'Audi', 'RS3', 'Sedan', 2026, 'new', 'RS3', 'Nardo Grey', 0, 345000, 'active',
      '["/vehicles/audi-rs3-sedan.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"Sedan"},{"id":"performance_line","name":"performance_line","value":"RS"},{"id":"model_family_key","name":"model_family_key","value":"rs3"},{"id":"sku_key","name":"sku_key","value":"audi-rs3-sedan"}]'::jsonb,
      'Audi RS3 Sedan', v_audi, now(), now()),
    ('audi-a5-sedan', 'Audi', 'A5', 'Sedan', 2026, 'new', 'A5', 'Florett Silver', 0, 235000, 'active',
      '["/vehicles/audi-a5-sedan.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"Sedan"},{"id":"performance_line","name":"performance_line","value":"A"},{"id":"model_family_key","name":"model_family_key","value":"a5"},{"id":"sku_key","name":"sku_key","value":"audi-a5-sedan"}]'::jsonb,
      'Audi A5 Sedan', v_audi, now(), now()),
    ('audi-rs5-avant', 'Audi', 'RS5', 'Avant', 2026, 'new', 'RS5', 'Nardo Grey', 0, 450000, 'active',
      '["/vehicles/audi-rs5-avant.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"Avant"},{"id":"performance_line","name":"performance_line","value":"RS"},{"id":"model_family_key","name":"model_family_key","value":"rs5"},{"id":"sku_key","name":"sku_key","value":"audi-rs5-avant"}]'::jsonb,
      'Audi RS5 Avant', v_audi, now(), now()),
    ('audi-rs5-sedan', 'Audi', 'RS5', 'Sedan', 2026, 'new', 'RS5', 'Nardo Grey', 0, 480000, 'active',
      '["/vehicles/audi-rs5-sedan.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"Sedan"},{"id":"performance_line","name":"performance_line","value":"RS"},{"id":"model_family_key","name":"model_family_key","value":"rs5"},{"id":"sku_key","name":"sku_key","value":"audi-rs5-sedan"}]'::jsonb,
      'Audi RS5 Sedan', v_audi, now(), now()),
    ('audi-a6', 'Audi', 'A6', 'Sedan', 2026, 'new', 'A6', 'Florett Silver', 0, 255000, 'active',
      '["/vehicles/audi-a6.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"Sedan"},{"id":"performance_line","name":"performance_line","value":"A"},{"id":"model_family_key","name":"model_family_key","value":"a6"},{"id":"sku_key","name":"sku_key","value":"audi-a6"}]'::jsonb,
      'Audi A6', v_audi, now(), now()),
    ('audi-a8l-55-tfsi', 'Audi', 'A8', 'L 55 TFSI', 2026, 'new', '55 TFSI', 'Florett Silver', 0, 465000, 'active',
      '["/vehicles/audi-a8l-55-tfsi.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"Sedan"},{"id":"performance_line","name":"performance_line","value":"A"},{"id":"model_family_key","name":"model_family_key","value":"a8"},{"id":"sku_key","name":"sku_key","value":"audi-a8l-55-tfsi"}]'::jsonb,
      'Audi A8L 55 TFSI', v_audi, now(), now()),
    ('audi-s8', 'Audi', 'S8', 'Sedan', 2026, 'new', 'S8', 'Daytona Grey', 0, 690000, 'active',
      '["/vehicles/audi-s8.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"Sedan"},{"id":"performance_line","name":"performance_line","value":"S"},{"id":"model_family_key","name":"model_family_key","value":"s8"},{"id":"sku_key","name":"sku_key","value":"audi-s8"}]'::jsonb,
      'Audi S8', v_audi, now(), now()),
    ('audi-q2', 'Audi', 'Q2', 'SUV', 2026, 'new', 'Q2', 'Florett Silver', 0, 155000, 'active',
      '["/vehicles/audi-q2.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"SUV"},{"id":"performance_line","name":"performance_line","value":"Q"},{"id":"model_family_key","name":"model_family_key","value":"q2"},{"id":"sku_key","name":"sku_key","value":"audi-q2"}]'::jsonb,
      'Audi Q2', v_audi, now(), now()),
    ('audi-q3-suv', 'Audi', 'Q3', 'SUV', 2026, 'new', 'Q3', 'Florett Silver', 0, 210000, 'active',
      '["/vehicles/audi-q3-suv.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"SUV"},{"id":"performance_line","name":"performance_line","value":"Q"},{"id":"model_family_key","name":"model_family_key","value":"q3"},{"id":"sku_key","name":"sku_key","value":"audi-q3-suv"}]'::jsonb,
      'Audi Q3 SUV', v_audi, now(), now()),
    ('audi-q3-sportback', 'Audi', 'Q3', 'Sportback', 2026, 'new', 'Q3', 'Florett Silver', 0, 240000, 'active',
      '["/vehicles/audi-q3-sportback.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"Sportback"},{"id":"performance_line","name":"performance_line","value":"Q"},{"id":"model_family_key","name":"model_family_key","value":"q3"},{"id":"sku_key","name":"sku_key","value":"audi-q3-sportback"}]'::jsonb,
      'Audi Q3 Sportback', v_audi, now(), now()),
    ('audi-q5-suv', 'Audi', 'Q5', 'SUV', 2026, 'new', 'Q5', 'Florett Silver', 0, 275000, 'active',
      '["/vehicles/audi-q5-suv.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"SUV"},{"id":"performance_line","name":"performance_line","value":"Q"},{"id":"model_family_key","name":"model_family_key","value":"q5"},{"id":"sku_key","name":"sku_key","value":"audi-q5-suv"}]'::jsonb,
      'Audi Q5 SUV', v_audi, now(), now()),
    ('audi-q5-sportback', 'Audi', 'Q5', 'Sportback', 2026, 'new', 'Q5', 'Florett Silver', 0, 295000, 'active',
      '["/vehicles/audi-q5-sportback.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"Sportback"},{"id":"performance_line","name":"performance_line","value":"Q"},{"id":"model_family_key","name":"model_family_key","value":"q5"},{"id":"sku_key","name":"sku_key","value":"audi-q5-sportback"}]'::jsonb,
      'Audi Q5 Sportback', v_audi, now(), now()),
    ('audi-sq5-suv', 'Audi', 'SQ5', 'SUV', 2026, 'new', 'SQ5', 'Daytona Grey', 0, 355000, 'active',
      '["/vehicles/audi-sq5-suv.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"SUV"},{"id":"performance_line","name":"performance_line","value":"SQ"},{"id":"model_family_key","name":"model_family_key","value":"sq5"},{"id":"sku_key","name":"sku_key","value":"audi-sq5-suv"}]'::jsonb,
      'Audi SQ5 SUV', v_audi, now(), now()),
    ('audi-sq5-sportback', 'Audi', 'SQ5', 'Sportback', 2026, 'new', 'SQ5', 'Daytona Grey', 0, 365000, 'active',
      '["/vehicles/audi-sq5-sportback.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"Sportback"},{"id":"performance_line","name":"performance_line","value":"SQ"},{"id":"model_family_key","name":"model_family_key","value":"sq5"},{"id":"sku_key","name":"sku_key","value":"audi-sq5-sportback"}]'::jsonb,
      'Audi SQ5 Sportback', v_audi, now(), now()),
    ('audi-q6-etron-suv', 'Audi', 'Q6', 'e-tron SUV', 2026, 'new', 'e-tron', 'Florett Silver', 0, 355000, 'active',
      '["/vehicles/audi-q6-etron-suv.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"SUV"},{"id":"performance_line","name":"performance_line","value":"Q"},{"id":"model_family_key","name":"model_family_key","value":"q6-etron"},{"id":"sku_key","name":"sku_key","value":"audi-q6-etron-suv"}]'::jsonb,
      'Audi Q6 e-tron SUV', v_audi, now(), now()),
    ('audi-q6-etron-sportback', 'Audi', 'Q6', 'e-tron Sportback', 2026, 'new', 'e-tron', 'Florett Silver', 0, 365000, 'active',
      '["/vehicles/audi-q6-etron-sportback.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"Sportback"},{"id":"performance_line","name":"performance_line","value":"Q"},{"id":"model_family_key","name":"model_family_key","value":"q6-etron"},{"id":"sku_key","name":"sku_key","value":"audi-q6-etron-sportback"}]'::jsonb,
      'Audi Q6 e-tron Sportback', v_audi, now(), now()),
    ('audi-q7-185-kw', 'Audi', 'Q7', '185 kW', 2026, 'new', '185 kW', 'Florett Silver', 0, 360000, 'active',
      '["/vehicles/audi-q7-185-kw.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"SUV"},{"id":"performance_line","name":"performance_line","value":"Q"},{"id":"model_family_key","name":"model_family_key","value":"q7"},{"id":"sku_key","name":"sku_key","value":"audi-q7-185-kw"}]'::jsonb,
      'Audi Q7 185 kW', v_audi, now(), now()),
    ('audi-q7-250-kw', 'Audi', 'Q7', '250 kW', 2026, 'new', '250 kW', 'Florett Silver', 0, 420000, 'active',
      '["/vehicles/audi-q7-250-kw.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"SUV"},{"id":"performance_line","name":"performance_line","value":"Q"},{"id":"model_family_key","name":"model_family_key","value":"q7"},{"id":"sku_key","name":"sku_key","value":"audi-q7-250-kw"}]'::jsonb,
      'Audi Q7 250 kW', v_audi, now(), now()),
    ('audi-q8-suv', 'Audi', 'Q8', 'SUV', 2026, 'new', 'Q8', 'Florett Silver', 0, 420000, 'active',
      '["/vehicles/audi-q8-suv.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"SUV"},{"id":"performance_line","name":"performance_line","value":"Q"},{"id":"model_family_key","name":"model_family_key","value":"q8"},{"id":"sku_key","name":"sku_key","value":"audi-q8-suv"}]'::jsonb,
      'Audi Q8 SUV', v_audi, now(), now()),
    ('audi-sq8', 'Audi', 'SQ8', 'SUV', 2026, 'new', 'SQ8', 'Daytona Grey', 0, 565000, 'active',
      '["/vehicles/audi-sq8.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"SUV"},{"id":"performance_line","name":"performance_line","value":"SQ"},{"id":"model_family_key","name":"model_family_key","value":"sq8"},{"id":"sku_key","name":"sku_key","value":"audi-sq8"}]'::jsonb,
      'Audi SQ8', v_audi, now(), now()),
    ('audi-rsq8', 'Audi', 'RSQ8', 'SUV', 2026, 'new', 'RSQ8', 'Nardo Grey', 0, 740000, 'active',
      '["/vehicles/audi-rsq8.webp"]'::jsonb, '[]'::jsonb,
      '[{"id":"body_style","name":"body_style","value":"SUV"},{"id":"performance_line","name":"performance_line","value":"RSQ"},{"id":"model_family_key","name":"model_family_key","value":"rsq8"},{"id":"sku_key","name":"sku_key","value":"audi-rsq8"}]'::jsonb,
      'Audi RS Q8', v_audi, now(), now())
  ON CONFLICT (id) DO UPDATE SET
    make = EXCLUDED.make,
    model = EXCLUDED.model,
    trim = EXCLUDED.trim,
    model_year = EXCLUDED.model_year,
    condition = EXCLUDED.condition,
    engine = EXCLUDED.engine,
    color = EXCLUDED.color,
    price = EXCLUDED.price,
    status = EXCLUDED.status,
    images = EXCLUDED.images,
    attributes = EXCLUDED.attributes,
    description = EXCLUDED.description,
    company_id = EXCLUDED.company_id,
    updated_at = now();
END $$;
