-- Seed customer catalog vehicles from catalog-seed.ts into products.
-- Idempotent: skip ids that already exist.

INSERT INTO public.products (
  id, make, model, trim, model_year, condition, engine, color, mileage, price,
  status, images, documents, attributes, description, created_at, updated_at
) VALUES
(
  'vehicle-56',
  'Changan',
  'Alsvin',
  'Basic',
  2026,
  'new',
  '1.5L I4',
  'White',
  0,
  39000,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v56-attr-0","name":"Transmission","value":"DCT"},{"id":"v56-attr-1","name":"Seating","value":"5 Seater"},{"id":"v56-attr-2","name":"Horsepower","value":"107"}]'::jsonb,
  'Compact sedan with 1.5L engine and dual-clutch automatic — entry-level value for daily commuting in Qatar.',
  now(),
  now()
),
(
  'vehicle-57',
  'Changan',
  'Alsvin',
  'Full Option',
  2026,
  'new',
  '1.5L I4',
  'Silver',
  0,
  40900,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v57-attr-0","name":"Transmission","value":"DCT"},{"id":"v57-attr-1","name":"Seating","value":"5 Seater"},{"id":"v57-attr-2","name":"Horsepower","value":"107"}]'::jsonb,
  'Feature-packed compact sedan with alloy wheels, reverse camera, and automatic climate control.',
  now(),
  now()
),
(
  'vehicle-58',
  'Changan',
  'Alsvin',
  'Full Option',
  2026,
  'new',
  '1.5L I4',
  'Red',
  0,
  41500,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v58-attr-0","name":"Transmission","value":"DCT"},{"id":"v58-attr-1","name":"Seating","value":"5 Seater"},{"id":"v58-attr-2","name":"Horsepower","value":"107"}]'::jsonb,
  'Sporty red compact sedan with modern LED lighting and dual-clutch transmission.',
  now(),
  now()
),
(
  'vehicle-59',
  'Toyota',
  'Yaris',
  'Sedan',
  2026,
  'new',
  '1.5L I4',
  'White',
  0,
  57000,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v59-attr-0","name":"Transmission","value":"CVT"},{"id":"v59-attr-1","name":"Seating","value":"5 Seater"},{"id":"v59-attr-2","name":"Fuel Efficiency","value":"20+ km/L"}]'::jsonb,
  'Trusted Toyota Yaris sedan — efficient, reliable, and built for Qatar roads.',
  now(),
  now()
),
(
  'vehicle-60',
  'Toyota',
  'Yaris',
  'Sedan',
  2026,
  'new',
  '1.5L I4',
  'Silver',
  0,
  58500,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v60-attr-0","name":"Transmission","value":"CVT"},{"id":"v60-attr-1","name":"Seating","value":"5 Seater"},{"id":"v60-attr-2","name":"Fuel Efficiency","value":"20+ km/L"}]'::jsonb,
  'Toyota Yaris sedan in metallic silver with CVT and strong resale value.',
  now(),
  now()
),
(
  'vehicle-61',
  'Toyota',
  'Yaris',
  'Sedan',
  2026,
  'new',
  '1.5L I4',
  'Black',
  0,
  59000,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v61-attr-0","name":"Transmission","value":"CVT"},{"id":"v61-attr-1","name":"Seating","value":"5 Seater"},{"id":"v61-attr-2","name":"Fuel Efficiency","value":"20+ km/L"}]'::jsonb,
  'Sleek black Toyota Yaris sedan with efficient 1.5L powertrain.',
  now(),
  now()
),
(
  'vehicle-62',
  'SEAT',
  'Ibiza',
  'Reference',
  2026,
  'new',
  '1.6L I4',
  'Red',
  0,
  55000,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v62-attr-0","name":"Transmission","value":"Automatic"},{"id":"v62-attr-1","name":"Seating","value":"5 Seater"},{"id":"v62-attr-2","name":"Body","value":"Hatchback"}]'::jsonb,
  'European hatchback with lively handling and compact city-friendly size.',
  now(),
  now()
),
(
  'vehicle-63',
  'SEAT',
  'Ibiza',
  'Style',
  2026,
  'new',
  '1.6L I4',
  'White',
  0,
  56000,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v63-attr-0","name":"Transmission","value":"Automatic"},{"id":"v63-attr-1","name":"Seating","value":"5 Seater"},{"id":"v63-attr-2","name":"Body","value":"Hatchback"}]'::jsonb,
  'SEAT Ibiza Style hatchback with premium cabin touches and automatic gearbox.',
  now(),
  now()
),
(
  'vehicle-64',
  'SEAT',
  'Ibiza',
  'Style',
  2026,
  'new',
  '1.6L I4',
  'Grey',
  0,
  59000,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v64-attr-0","name":"Transmission","value":"Automatic"},{"id":"v64-attr-1","name":"Seating","value":"5 Seater"},{"id":"v64-attr-2","name":"Body","value":"Hatchback"}]'::jsonb,
  'Grey SEAT Ibiza Style — modern hatch with fog lights and power features.',
  now(),
  now()
),
(
  'vehicle-65',
  'Chery',
  'Tiggo 4',
  'Comfort',
  2026,
  'new',
  '1.5L Turbo',
  'White',
  0,
  62000,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v65-attr-0","name":"Transmission","value":"CVT"},{"id":"v65-attr-1","name":"Seating","value":"5 Seater"},{"id":"v65-attr-2","name":"Body","value":"SUV"}]'::jsonb,
  'Compact SUV with elevated ride height, turbo engine, and family-friendly space.',
  now(),
  now()
),
(
  'vehicle-66',
  'Chery',
  'Tiggo 4',
  'Comfort',
  2026,
  'new',
  '1.5L Turbo',
  'Grey',
  0,
  63500,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v66-attr-0","name":"Transmission","value":"CVT"},{"id":"v66-attr-1","name":"Seating","value":"5 Seater"},{"id":"v66-attr-2","name":"Body","value":"SUV"}]'::jsonb,
  'Chery Tiggo 4 compact SUV in grey — reverse camera, parking sensors, and modern tech.',
  now(),
  now()
),
(
  'vehicle-67',
  'Chery',
  'Tiggo 4',
  'Luxury',
  2026,
  'new',
  '1.5L Turbo',
  'Blue',
  0,
  65000,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v67-attr-0","name":"Transmission","value":"CVT"},{"id":"v67-attr-1","name":"Seating","value":"5 Seater"},{"id":"v67-attr-2","name":"Body","value":"SUV"}]'::jsonb,
  'Blue Chery Tiggo 4 Luxury compact SUV with enriched features and turbo performance.',
  now(),
  now()
),
(
  'vehicle-68',
  'Suzuki',
  'Dzire',
  'GL',
  2026,
  'new',
  '1.2L I4',
  'White',
  0,
  39900,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v68-attr-0","name":"Transmission","value":"Automatic"},{"id":"v68-attr-1","name":"Seating","value":"5 Seater"},{"id":"v68-attr-2","name":"Fuel Efficiency","value":"High"}]'::jsonb,
  'Ultra-efficient compact sedan ideal for first-time buyers and city driving.',
  now(),
  now()
),
(
  'vehicle-69',
  'Suzuki',
  'Dzire',
  'GLX',
  2026,
  'new',
  '1.2L I4',
  'Blue',
  0,
  41900,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v69-attr-0","name":"Transmission","value":"Automatic"},{"id":"v69-attr-1","name":"Seating","value":"5 Seater"},{"id":"v69-attr-2","name":"Fuel Efficiency","value":"High"}]'::jsonb,
  'Suzuki Dzire GLX in blue with upgraded trim and automatic transmission.',
  now(),
  now()
),
(
  'vehicle-70',
  'MG',
  'ZS',
  'Standard',
  2026,
  'new',
  '1.5L I4',
  'White',
  0,
  54900,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v70-attr-0","name":"Transmission","value":"CVT"},{"id":"v70-attr-1","name":"Seating","value":"5 Seater"},{"id":"v70-attr-2","name":"Body","value":"Crossover SUV"}]'::jsonb,
  'Compact MG ZS crossover — stylish SUV stance with sedan-like efficiency.',
  now(),
  now()
),
(
  'vehicle-71',
  'MG',
  'ZS',
  'Luxury',
  2026,
  'new',
  '1.5L I4',
  'Red',
  0,
  56900,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v71-attr-0","name":"Transmission","value":"CVT"},{"id":"v71-attr-1","name":"Seating","value":"5 Seater"},{"id":"v71-attr-2","name":"Body","value":"Crossover SUV"}]'::jsonb,
  'MG ZS Luxury in red with touchscreen infotainment and elevated seating.',
  now(),
  now()
),
(
  'vehicle-72',
  'Hyundai',
  'Accent',
  'Smart',
  2026,
  'new',
  '1.6L I4',
  'Silver',
  0,
  59900,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v72-attr-0","name":"Transmission","value":"Automatic"},{"id":"v72-attr-1","name":"Seating","value":"5 Seater"},{"id":"v72-attr-2","name":"Horsepower","value":"123"}]'::jsonb,
  'Hyundai Accent Smart — mainstream sedan with warranty confidence and solid features.',
  now(),
  now()
),
(
  'vehicle-73',
  'Hyundai',
  'Accent',
  'Comfort',
  2026,
  'new',
  '1.6L I4',
  'White',
  0,
  62900,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v73-attr-0","name":"Transmission","value":"Automatic"},{"id":"v73-attr-1","name":"Seating","value":"5 Seater"},{"id":"v73-attr-2","name":"Horsepower","value":"123"}]'::jsonb,
  'White Hyundai Accent Comfort sedan with automatic gearbox and family practicality.',
  now(),
  now()
),
(
  'vehicle-74',
  'Chery',
  'Arrizo 5',
  'Comfort',
  2026,
  'new',
  '1.5L I4',
  'White',
  0,
  53000,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v74-attr-0","name":"Transmission","value":"CVT"},{"id":"v74-attr-1","name":"Seating","value":"5 Seater"},{"id":"v74-attr-2","name":"Body","value":"Sedan"}]'::jsonb,
  'Chery Arrizo 5 Comfort sedan — spacious cabin and competitive equipment list.',
  now(),
  now()
),
(
  'vehicle-75',
  'Chery',
  'Arrizo 5',
  'Comfort',
  2026,
  'new',
  '1.5L I4',
  'Grey',
  0,
  54000,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v75-attr-0","name":"Transmission","value":"CVT"},{"id":"v75-attr-1","name":"Seating","value":"5 Seater"},{"id":"v75-attr-2","name":"Body","value":"Sedan"}]'::jsonb,
  'Grey Chery Arrizo 5 Comfort compact sedan for everyday Qatar commuting.',
  now(),
  now()
),
(
  'vehicle-76',
  'MG',
  '5',
  'Standard',
  2026,
  'new',
  '1.5L V4',
  'White',
  0,
  42000,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v76-attr-0","name":"Transmission","value":"CVT"},{"id":"v76-attr-1","name":"Seating","value":"5 Seater"},{"id":"v76-attr-2","name":"Horsepower","value":"112"},{"id":"v76-attr-3","name":"Trunk Capacity","value":"512"}]'::jsonb,
  'MG 5 sedan in white — stylish compact with CVT and generous trunk space.',
  now(),
  now()
),
(
  'vehicle-77',
  'MG',
  '5',
  'Standard',
  2026,
  'new',
  '1.5L V4',
  'Blue',
  0,
  42500,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v77-attr-0","name":"Transmission","value":"CVT"},{"id":"v77-attr-1","name":"Seating","value":"5 Seater"},{"id":"v77-attr-2","name":"Horsepower","value":"112"},{"id":"v77-attr-3","name":"Trunk Capacity","value":"512"}]'::jsonb,
  'MG 5 sedan in blue with modern grille and LED lighting.',
  now(),
  now()
),
(
  'vehicle-78',
  'Geely',
  'Emgrand',
  'GS',
  2026,
  'new',
  '1.5L',
  'White',
  0,
  49900,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v78-attr-0","name":"Transmission","value":"CVT"},{"id":"v78-attr-1","name":"Seating","value":"5 Seater"},{"id":"v78-attr-2","name":"Torque","value":"142"},{"id":"v78-attr-3","name":"Fuel Tank Capacity","value":"50L"}]'::jsonb,
  'Geely Emgrand GS in white — compact sedan with 12.3-inch screen and CVT.',
  now(),
  now()
),
(
  'vehicle-79',
  'Geely',
  'Emgrand',
  'GK',
  2026,
  'new',
  '1.5L',
  'Black',
  0,
  58000,
  'active',
  '[]'::jsonb,
  '[]'::jsonb,
  '[{"id":"v79-attr-0","name":"Transmission","value":"CVT"},{"id":"v79-attr-1","name":"Seating","value":"5 Seater"},{"id":"v79-attr-2","name":"Torque","value":"142"},{"id":"v79-attr-3","name":"Fuel Tank Capacity","value":"50L"}]'::jsonb,
  'Geely Emgrand GK in black — higher trim with enriched comfort and safety features.',
  now(),
  now()
)
ON CONFLICT (id) DO NOTHING;
